"""Fault-state, collection, enlarged-text and long-content UI checks with synthetic data."""
import argparse
import json
from pathlib import Path
from playwright.sync_api import expect, sync_playwright
ROOT = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--axe", type=Path, required=True, help="Local axe-core JavaScript bundle")
parser.add_argument("--output", type=Path, default=ROOT / ".cache/operational-ux")
args = parser.parse_args()
OUTPUT = args.output
(OUTPUT / "screenshots").mkdir(parents=True, exist_ok=True)
FIXTURE = (Path(__file__).parent / "fixtures.js").read_text()
AXE = args.axe
checks = []
violations = []

def capture(page, name):
    # A full-page capture resizes the viewport and correctly dismisses open menus.
    page.screenshot(path=str(OUTPUT / "screenshots" / f"operational-{name}.png"), full_page=page.get_by_role("menu").count() == 0)
    assert page.evaluate("document.documentElement.scrollWidth <= innerWidth"), name
    page.add_script_tag(path=str(AXE))
    results = page.evaluate("async () => await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a','wcag2aa','wcag21aa','wcag22aa'] } })")
    if results["violations"]:
        (OUTPUT / f"accessibility-{name}.json").write_text(json.dumps(results["violations"], indent=2))
    violations.extend({"screen": name, "id": item["id"], "nodes": [n["target"] for n in item["nodes"]]} for item in results["violations"])

expect.set_options(timeout=10000)
with sync_playwright() as pw:
    browser = pw.chromium.launch()
    page = browser.new_page(viewport={"width": 1220, "height": 780}, reduced_motion="reduce")
    page.add_init_script('window.__sirinPlatform="desktop"; window.__sirinScenario="connected";' + FIXTURE)
    page.goto("http://127.0.0.1:1420", wait_until="networkidle")
    nav = page.get_by_role("navigation", name="Main navigation")
    expect(page.locator(".device-traffic .metric").first.locator("strong")).to_contain_text("KB/s", timeout=10000)
    capture(page, "live-device-rates")
    checks.append("Device rates derive from consecutive local counters")
    page.evaluate("window.__sirinRemoteFails = true")
    expect(page.get_by_text("VPN connected · Server metrics unavailable")).to_be_visible()
    expect(page.get_by_role("button", name="Disconnect", exact=True)).to_be_enabled()
    capture(page, "management-unavailable")
    checks.append("Management failure preserves connected tunnel and device metrics")
    nav.get_by_role("button", name="Settings", exact=False).click()
    page.get_by_role("tab", name="Network", exact=True).click()
    expect(page.get_by_text("VPS DNS configuration is unavailable. The local VPN remains connected.")).to_be_visible()
    checks.append("Network settings distinguish unavailable DNS measurements from a disconnected tunnel")
    nav.get_by_role("button", name="Home", exact=False).click()
    page.evaluate("window.__sirinLocalFails = true")
    expect(page.get_by_role("button", name="Refresh status", exact=True)).to_be_visible()
    expect(page.locator(".connection-facts")).to_contain_text("Unknown")
    expect(page.get_by_role("button", name="Connect", exact=True)).to_have_count(0)
    capture(page, "local-unknown")
    checks.append("Unknown local state does not become disconnected or protection Off")
    page.evaluate("window.__sirinLocalFails = false; window.__sirinRemoteFails = false; window.__sirinLocalOverride = {state:'degraded',kill_switch_enabled:true,auto_reconnect_enabled:true}")
    page.get_by_role("button", name="Refresh status").click()
    expect(page.get_by_role("button", name="Disconnect & release block", exact=True)).to_be_visible()
    expect(page.locator(".connection-facts")).to_contain_text("enforcement unverified")
    capture(page, "reconnecting")
    checks.append("Reconnecting reports configured protection without claiming firewall verification")
    page.evaluate("window.__sirinLocalOverride = {}")
    nav.get_by_role("button", name="Settings", exact=False).click()
    page.get_by_role("tab", name="General", exact=True).click()
    page.evaluate("window.__sirinPreferenceFails = true")
    page.get_by_role("switch", name="Close to tray").click()
    expect(page.get_by_role("alert")).to_contain_text("Preference save failed")
    expect(page.get_by_role("switch", name="Close to tray")).not_to_be_checked()
    capture(page, "preference-failure")
    checks.append("Failed preference save keeps prior value and explains failure beside control")
    page.evaluate("window.__sirinPreferenceFails = false")
    nav.get_by_role("button", name="Servers", exact=False).click()
    page.get_by_role("button", name="Actions for My private VPS").click()
    page.get_by_role("menuitem", name="Add favorite", exact=True).click()
    page.get_by_role("button", name="Actions for My private VPS").click()
    expect(page.get_by_role("menuitem", name="Remove favorite", exact=True)).to_be_visible()
    page.once("dialog", lambda dialog: dialog.accept("Home server"))
    page.get_by_role("menuitem", name="Rename locally").click()
    expect(page.get_by_role("heading", name="Favorite Home server", exact=True)).to_be_visible()
    checks.append("Collection rename and favorite actions use native API, independent of connection")
    page.get_by_role("button", name="Open", exact=True).click()
    expect(page.get_by_role("button", name="Disconnect", exact=True)).to_be_visible()
    page.evaluate("async () => { const [profile] = await window.__TAURI_INTERNALS__.invoke('list_servers'); window.__sirinProfiles = [profile, {...profile, id:'other', name:'Second server'}]; }")
    nav.get_by_role("button", name="Servers", exact=False).click()
    page.get_by_role("button", name="Actions for Home server").click()
    page.get_by_role("menuitem", name="Remove favorite", exact=True).click()
    page.locator(".collection-row").filter(has_text="Second server").get_by_role("button", name="Open", exact=True).click()
    expect(page.get_by_role("button", name="Connect", exact=True)).to_be_disabled()
    expect(page.get_by_text("Another server is active.", exact=False)).to_be_visible()
    checks.append("Selecting another profile does not change or mislabel the existing tunnel")
    page.close()
    # Resize every rendered text style, rather than relying on device pixel scaling.
    for screen in ["Home", "Devices", "Settings", "Servers"]:
        page = browser.new_page(viewport={"width": 1220, "height": 780}, reduced_motion="reduce")
        page.add_init_script('window.__sirinPlatform="desktop"; window.__sirinScenario="connected";' + FIXTURE)
        page.goto("http://127.0.0.1:1420", wait_until="networkidle")
        page.get_by_role("navigation", name="Main navigation").get_by_role("button", name=screen, exact=False).click()
        if screen == "Settings": page.get_by_role("tab", name="Network", exact=True).click()
        page.evaluate("""() => { const sizes = Array.from(document.querySelectorAll('*')).map(el => [el, parseFloat(getComputedStyle(el).fontSize)]); sizes.forEach(([el,size]) => el.style.fontSize = `${size*2}px`); }""")
        capture(page, screen.lower() + "-text-200")
        clipped = page.locator(".metric strong, .device-row-copy, .connection-center button, .collection-copy, .settings-card, .port-forward-form, .primary-navigation button, .brand, .server-row small").evaluate_all("els => els.filter(el => el.getBoundingClientRect().width && el.scrollWidth > el.clientWidth + 2).map(el => ({class: el.className, width:el.clientWidth, scroll:el.scrollWidth}))")
        assert not clipped, (screen, clipped)
        fields = page.locator(".port-forward-form input, .port-forward-form select").evaluate_all("els => els.filter(el => el.getBoundingClientRect().height && el.clientHeight < parseFloat(getComputedStyle(el).fontSize) * 1.5 + 12).map(el => el.outerHTML)")
        assert not fields, (screen, "Vertically clipped text in fields", fields)
        checks.append(f"{screen}: 200% text has no clipped operational controls or metrics")
        page.close()
    page = browser.new_page(viewport={"width": 390, "height": 844}, reduced_motion="reduce")
    page.add_init_script('window.__sirinPlatform="desktop"; window.__sirinScenario="connected";' + FIXTURE + "\nwindow.__sirinMembership = { members: Array.from({length:18}, (_, i) => ({id:String(i),name:'Family member '+i,role:'member',devices:[{id:'device-'+i,name:'My very long Android device name for work and travel '+i,client_tunnel_address:'10.77.0.'+(i+2),identity_fingerprint:'0123456789abcdef'.repeat(4)}]})),active_invitations:[],port_forwards:[]};")
    page.goto("http://127.0.0.1:1420", wait_until="networkidle")
    page.get_by_role("navigation", name="Mobile navigation").get_by_role("button", name="Devices", exact=False).click()
    expect(page.locator(".device-row")).to_have_count(18)
    page.locator(".device-row-summary").first.click()
    page.locator(".device-row").first.get_by_role("button", name="Show full").click()
    page.locator(".device-row").first.get_by_role("button", name="Actions for", exact=False).click()
    capture(page, "long-mobile-devices")
    checks.append("18 long-named devices, full fingerprint, and action menu fit mobile width")
    page.mouse.click(8, 80)
    expect(page.get_by_role("menu")).to_have_count(0)
    assert not page.locator(".device-row-details").first.evaluate("el=>el.inert")
    expect(page.locator(".device-row").first.get_by_role("button", name="Shorten", exact=True)).to_be_visible()
    checks.append("Dismissal restores detail controls; menu background cannot trigger partly covered actions")
    last = page.locator(".device-row").last
    last.get_by_role("button", name="Actions for", exact=False).click()
    menu = page.get_by_role("menu").bounding_box()
    nav_box = page.locator(".bottom-navigation").bounding_box()
    assert menu["y"] >= 0 and menu["y"] + menu["height"] <= nav_box["y"], (menu, nav_box)
    capture(page, "bottom-device-menu")
    checks.append("The last device's menu opens above its row and stays clear of bottom navigation")
    page.close()
    browser.close()
(OUTPUT / "operational-checks.json").write_text(json.dumps({"checks": checks, "accessibility": violations}, indent=2) + "\n")
assert not violations, violations
print(json.dumps(checks, indent=2))
