"""Operational refinements: real DOM interactions with synthetic native responses."""
import json
from pathlib import Path
from playwright.sync_api import expect, sync_playwright

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / ".cache/refinement"
FIXTURE = Path(__file__).with_name("fixtures.js").read_text()
checks = []
with sync_playwright() as pw:
    browser = pw.chromium.launch()
    page = browser.new_page(viewport={"width":1220,"height":780}, reduced_motion="reduce")
    page.add_init_script('window.__sirinPlatform="desktop";window.__sirinScenario="connected";' + FIXTURE)
    page.goto("http://127.0.0.1:1420", wait_until="networkidle")
    nav = page.get_by_role("navigation", name="Main navigation")
    expect(page.locator(".device-traffic .metric").first.locator("strong")).to_contain_text("KB/s", timeout=10000)
    assert page.locator(".resource-grid").evaluate("el => el.getBoundingClientRect().bottom <= innerHeight"), "Ordinary summary extends below the window"
    widths = page.locator(".resource-grid meter").evaluate_all("els => els.map(el => el.getBoundingClientRect().width)")
    assert max(widths) - min(widths) < 1, widths
    expect(page.locator(".connection-facts")).to_contain_text("Management response")
    expect(page.locator(".primary-navigation small")).to_have_count(0)
    page.screenshot(path=str(OUTPUT / "home-viewport.png"))
    checks.append("At 1220×780, device traffic and complete VPS summary fit; resource tracks are equal width")
    nav.get_by_role("button", name="Settings", exact=True).click()
    page.get_by_role("tab", name="Connection", exact=True).click()
    positions = page.locator(".condition-choices .choice-row").evaluate_all("els => els.map(el => ({x:el.offsetLeft,y:el.offsetTop}))")
    assert len(positions) == 4 and positions[0]["y"] == positions[1]["y"] and positions[2]["y"] == positions[3]["y"] and positions[0]["x"] == positions[2]["x"]
    page.get_by_role("switch", name="Choose transport automatically").uncheck()
    page.get_by_role("radio", name="TCP fallback", exact=False).check()
    expect(page.get_by_text("Unsaved connection preferences", exact=True)).to_be_visible()
    page.get_by_role("button", name="Save preferences", exact=True).click()
    expect(page.locator(".pending-preferences")).to_contain_text("Transport: Direct UDP")
    page.reload(wait_until="networkidle")
    nav.get_by_role("button", name="Settings", exact=True).click()
    page.get_by_role("tab", name="Connection", exact=True).click()
    expect(page.get_by_role("radio", name="TCP fallback", exact=False)).to_be_checked()
    checks.append("Network-condition choices use a 2×2 layout; saved transport survives reload and distinguishes the running Direct UDP connection")
    page.evaluate("window.__sirinConnectionSaveFails = true")
    page.get_by_role("radio", name="Direct UDP", exact=False).check()
    page.get_by_role("button", name="Save preferences", exact=True).click()
    expect(page.get_by_role("alert")).to_contain_text("Connection preference save failed")
    expect(page.get_by_text("Unsaved connection preferences", exact=True)).to_be_visible()
    page.get_by_role("button", name="Discard", exact=True).click()
    expect(page.get_by_role("radio", name="TCP fallback", exact=False)).to_be_checked()
    page.evaluate("window.__sirinConnectionSaveFails = false")
    checks.append("Failed saves leave previous preferences stored and the draft visibly unsaved; Discard restores the previous save")
    page.get_by_role("tab", name="Network", exact=True).click()
    page.get_by_role("radio", name="Selected routes", exact=False).check()
    page.locator(".route-list-field textarea").fill("198.51.100.0/24\n203.0.113.0/24")
    page.get_by_role("switch", name="Allow local network", exact=True).check()
    page.get_by_role("button", name="Save preferences", exact=True).click()
    page.reload(wait_until="networkidle")
    nav.get_by_role("button", name="Settings", exact=True).click()
    page.get_by_role("tab", name="Network", exact=True).click()
    expect(page.locator(".route-list-field textarea")).to_have_value("198.51.100.0/24\n203.0.113.0/24")
    expect(page.get_by_role("switch", name="Allow local network", exact=True)).to_be_checked()
    checks.append("Routing ranges and LAN bypass survive page reload as saved next-connection preferences")
    preview = page.get_by_label("Mapping preview")
    page.get_by_label("Public port", exact=True).evaluate("el => { const tabs=document.querySelector('.settings-tabs').getBoundingClientRect(); window.scrollBy(0, el.getBoundingClientRect().top-tabs.bottom+10); el.focus({preventScroll:true}); }")
    page.wait_for_function("document.activeElement.getBoundingClientRect().top >= document.querySelector('.settings-tabs').getBoundingClientRect().bottom")
    checks.append("Programmatically focused networking controls remain visible below sticky settings tabs")
    expect(preview).to_have_text("Enter both ports to preview the forwarding rule.")
    expect(page.get_by_label("Public port", exact=True)).to_have_value("")
    page.get_by_label("Public port", exact=True).fill("48080")
    page.get_by_label("Device port", exact=True).fill("8080")
    expect(preview).to_have_text("Public TCP port 48080 → My Linux desktop → port 8080")
    page.once("dialog", lambda dialog: dialog.accept())
    page.get_by_role("button", name="Open port", exact=True).click()
    args = page.evaluate("window.__sirinCommandArguments.findLast(item => item.command === 'create_port_forward').args")
    assert args["input"]["public_port"] == 48080 and args["input"]["device_port"] == 8080, args
    checks.append("Empty port placeholders are explicit; the complete preview and submitted mapping use the same inputs")
    page.get_by_role("tab", name="VPS maintenance", exact=True).click()
    expect(page.get_by_role("button", name="Run diagnostics", exact=True)).to_have_count(1)
    page.get_by_role("button", name="Update VPS software", exact=False).click()
    dialog = page.get_by_role("dialog")
    expect(dialog.get_by_role("button", name="Continue to VPS setup")).to_be_disabled()
    expect(dialog).to_contain_text("on this computer")
    assert not page.evaluate("window.__sirinCommands.some(command => command === 'repair_server' || command === 'probe_host_key')")
    dialog.get_by_role("button", name="Disconnect this computer", exact=True).click()
    expect(dialog.get_by_role("button", name="Continue to VPS setup")).to_be_enabled()
    dialog.get_by_role("button", name="Continue to VPS setup").click()
    expect(page.get_by_role("dialog")).to_contain_text("Update My private VPS")
    page.keyboard.press("Escape")
    checks.append("Connected maintenance opens a read-only plan; only an explicit local disconnect unlocks SSH setup")
    nav.get_by_role("button", name="Home", exact=True).click()
    page.evaluate("window.__sirinLocalOverride = {state:'connected',server_id:'123e4567-e89b-42d3-a456-426614174000',traffic_metrics_supported:false,counter_epoch:undefined,tunnel_uptime_seconds:undefined}")
    page.get_by_role("button", name="Refresh current state").click()
    expect(page.locator(".device-traffic .metric").first.locator("strong")).to_have_text("Unavailable")
    page.get_by_role("button", name="Review update", exact=True).click()
    expect(page.get_by_role("dialog")).to_contain_text("disconnect this device")
    page.get_by_role("button", name="Review app update", exact=True).click()
    expect(page.get_by_role("dialog")).to_contain_text("Check for app updates")
    page.keyboard.press("Escape")
    checks.append("A legacy helper gets explicit unavailable measurements and an actionable app-update review")
    page.evaluate("window.__sirinLocalOverride.traffic_metrics_supported = true; window.__sirinLocalOverride.byte_counters_available = false")
    page.get_by_role("button", name="Refresh current state").click()
    expect(page.get_by_text("Counter reading failed")).to_have_count(2)
    expect(page.get_by_role("button", name="Review update", exact=True)).to_have_count(0)
    expect(page.locator(".device-traffic")).not_to_contain_text("0 B/s")
    checks.append("Measurement failure is distinct from an old helper and never becomes measured zero traffic")
    browser.close()
(OUTPUT / "refinement-checks.json").write_text(json.dumps(checks, indent=2) + "\n")
print(json.dumps(checks, indent=2))
